# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yA-cb7JozrTN3GaMLwhWENbCnqeB2YC_
"""

from fer import FER
import cv2

img = cv2.imread("/content/pic22.jpg")
detector = FER()
detector.detect_emotions(img)
emotion, score = detector.top_emotion(img)
score
emotion

from pyagender import PyAgender
agender = PyAgender()
faces = agender.detect_genders_ages(cv2.imread("/content/pic22.jpg"))
faces